### ISSUE TITLE
Cannot create an instance of IPartnerCredentials

### ISSUE THREAD

**Issue by chrisvensand** [microsoft/Partner-Center-Java#130]
# Steps to reproduce

Tried to create an instance of IPartnerCredentials using the generateByApplicationCredentials method. After giving the method my clientId, applicationSecret and aadApplicationDomain from the partner center portal I recieved an error saying "Failed to do the application AAD login".

## Expected behavior

Recieve an instance of IPartnerCredentials.

## Actual behavior

Recieved an error message saying "Failed to do the application AAD login".

## Diagnostic logs

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Failed to do the application AAD login

Process finished with exit code 0
```

## Environment

Java Version 11
Using the "com.microsoft.store:partnercenter:1.15.3" maven repository.

**Comment by isaiahwilliams** [comment]
@chrisvensand can you share the code you are using to create the credential object?

**Comment by chrisvensand** [comment]
@isaiahwilliams yes below is the test project I am working with.

`

    import com.microsoft.store.partnercenter.IAggregatePartner;
    import com.microsoft.store.partnercenter.IPartnerCredentials;
    import com.microsoft.store.partnercenter.PartnerService;
    import com.microsoft.store.partnercenter.enumerators.IResourceCollectionEnumerator;
    import com.microsoft.store.partnercenter.extensions.PartnerCredentials;
    import com.microsoft.store.partnercenter.models.ResourceCollection;
    import com.microsoft.store.partnercenter.models.SeekBasedResourceCollection;
    import com.microsoft.store.partnercenter.models.customers.Customer;
    import com.microsoft.store.partnercenter.models.utilizations.AzureUtilizationGranularity;
    import com.microsoft.store.partnercenter.models.utilizations.AzureUtilizationRecord;
    import org.joda.time.DateTime;
    
    public class Main {
    
        public static void main(String[] args) {
            Main.testGetAzureUtilizationRecord();
        }
    
        public static void testGetAzureUtilizationRecord() {
    
            // Application credentials
            String aadApplicationId = "xxx"; /* The application identifier in Azure Active Directory. */
            String aadApplicationSecret = "xxx"; /* The application secret in Azure Active Directory. */
            String aadApplicationDomain = "xxx"; /* The application domain in Azure Active Directory. */
    
            try {
    
                IPartnerCredentials partnerCredentials =
                    PartnerCredentials.getInstance().generateByApplicationCredentials(
                        aadApplicationId,
                        aadApplicationSecret,
                        aadApplicationDomain);
    
                IAggregatePartner partnerOperations = PartnerService.getInstance()
                    .createPartnerOperations(partnerCredentials);
    
                SeekBasedResourceCollection<Customer> customers = partnerOperations.getCustomers()
                    .get();
    
                // Get the utilization records for one customer
                String customerId = new String();
                String subscriptionId = new String();
                ResourceCollection<AzureUtilizationRecord> utilizationRecords = partnerOperations
                    .getCustomers()
                    .byId(customerId /* customer we are interested in */)
                    .getSubscriptions()
                    .byId(subscriptionId /* subscription for the customer we are interested in */)
                    .getUtilization().getAzure().query(
                        new DateTime().minusYears(1),
                        new DateTime(),
                        AzureUtilizationGranularity.DAILY,
                        true,
                        100);
    
                // Create an Azure utilization enumerator which will aid us in traversing the utilization pages
                IResourceCollectionEnumerator<ResourceCollection<AzureUtilizationRecord>> utilizationRecordEnumerator =
                    partnerOperations.getEnumerators().getUtilization().getAzure()
                        .create(utilizationRecords);
    
                while (utilizationRecordEnumerator.hasValue()) {
                    //
                    // Insert code here to work with this page.
                    //
    
                    // get the next page
                    utilizationRecordEnumerator.next();
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }

`

**Comment by chrisvensand** [comment]
Any update on this?

**Comment by msize** [comment]
@chrisvensand 

I'm can't reproduce this issue. Provided code is working and Access Token was returned. Could you repeat and attache the full stack trace?

**Comment by chrisvensand** [comment]
@msize Thank you for the response. Maybe it is an issue with the credentials I am using. I will try to get a stack trace.

**Comment by chrisvensand** [comment]
@msize I wasn't able to get a stack trace. Maybe I am confused by the documentation [https://docs.microsoft.com/en-us/java/partnercenter/get-started?view=partnercenter-java-latest](here). Can I use App only authentication to retrieve analytics data about a csp account or do I need App + user authentication?

Is aadApplicationId,  aadApplicationSecret and the aadApplicationDomain supposed to come from the aad app created through the CSP portal? Where are these values displayed in the Azure Active Directory portal?

Thank you!

**Comment by msize** [comment]
@chrisvensand You can ask in Yammer in the Partner Center SDK and API group.

**Comment by msize** [comment]
@isaiahwilliams This issue I guess should be closed as not reproducible.

**Comment by chrisvensand** [comment]
@msize I have tried to join the Microsoft Cloud Yammer Community, but I was denied access. Someone named Renee Gallant-McKay told me the community is only for verified CSP Direct Bill partners and CSP Indirect Providers.

I work at LogicMonitor Inc. and we are trying to add monitoring capabilities for Azure CSP Billing data and our customers have CSP accounts.

**Comment by manuelmazzuola** [comment]
Hi i have the same issue, it works with `1.15.2`
There are some changes in the `1.15.3` version that don't allow me to login

```
val appCredentials = PartnerCredentials
                    .getInstance()
                    .generateByApplicationCredentials(
                            appId,
                            secret,
                            resellerDomain
                    )
```


```
com.microsoft.store.partnercenter.exception.PartnerException: Failed to do the application AAD login
	at com.microsoft.store.partnercenter.extensions.ApplicationPartnerCredentials.authenticate(ApplicationPartnerCredentials.java:174)

java.lang.ArrayIndexOutOfBoundsException: 0
	at com.microsoft.aad.msal4j.Authority.getTenant(Authority.java:88)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.sendInstanceDiscoveryRequest(AadInstanceDiscoveryProvider.java:110)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.doInstanceDiscoveryAndCache(AadInstanceDiscoveryProvider.java:131)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.getMetadataEntry(AadInstanceDiscoveryProvider.java:42)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.getAuthorityWithPrefNetworkHost(AuthenticationResultSupplier.java:32)
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:49)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1604)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

![image](https://user-images.githubusercontent.com/1757492/96736333-c97b1c00-13bc-11eb-849a-95c23d9f1d70.png)


EDIT

it works if i change the code to 

```
val appCredentials = PartnerCredentials
                    .getInstance()
                    .generateByApplicationCredentials(
                            appId,
                            secret,
                            resellerDomain,
                            "https://login.microsoftonline.com/${resellerDomain}/",
                            "https://graph.windows.net"
                    )
```

You should document that into a migration note
